language: swift
osx_image: xcode11
script: set -o pipefail && pod install && xcodebuild -workspace gRPC-PoC.xcworkspace -scheme gRPC-PoC -destination platform\=iOS\ Simulator,OS\=13.0,name\=iPhone\ XÊ€ build test LIGHTWALLETD-ADDRESS=$(LIGHTWALLETD-ADDRESS) | xcpretty